import {
    faBox, faCoffee, faCheckCircle, faTimesCircle, faUser, faHome, faSearch, faBell, faEnvelope,
    faAngleRight, faAngleLeft, faArrowUp, faArrowDown, faArrowLeft, faArrowRight, faCaretUp,
    faCaretDown, faCaretLeft, faCaretRight, faEdit, faTrash, faSave, faDownload, faUpload,
    faPlus, faMinus, faExclamationCircle, faInfoCircle, faQuestionCircle, faStar, faHeart,
    faThumbsUp, faThumbsDown, faComment, faShare, faEye, faEyeSlash, faLock, faUnlock, faPrint,
    faSignInAlt, faSignOutAlt, faSync, faCog, faWrench, faList, faTable, faChartBar, faChartPie,
    faChartLine, faMap, faMapMarker, faMapPin, faGlobe, faClock, faCalendar, faEnvelopeOpen,
    faEnvelopeSquare, faPhone, faPhoneSquare, faMobile, faTablet, faLaptop, faDesktop, faHeadphones,
    faVolumeUp, faVolumeDown, faVolumeMute, faMusic, faVideo, faCamera, faMicrophone, faMicrophoneSlash,
    faPlay, faPause, faStop, faForward, faBackward, faFastForward, faFastBackward, faStepForward,
    faStepBackward, faCircle, faSquare, faCheckSquare, faTimesSquare, faChevronUp, faChevronDown,
    faChevronLeft, faChevronRight, faBars, faTh, faThLarge, faThList, faSpinner, faEllipsisH,
    faEllipsisV, faCaretSquareUp, faCaretSquareDown, faCaretSquareLeft, faCaretSquareRight, faPen,
    faPenAlt, faPenSquare, faPenNib, faHighlighter, faPencil, faPencilAlt, faPencilSquare,
    faPencilRuler, faRuler, faRulerCombined, faRulerHorizontal, faRulerVertical, faDraftingCompass,
    faCompass, faPaintBrush, faPaintRoller, faPalette, faBrush, faSprayCan, faEraser, faStamp,
    faCut, faCopy, faPaste, faClipboard, faClipboardCheck, faClipboardList, faClipboardUser,
    faStickyNote, faTag, faTags, faBook, faBookmark, faFolder, faFolderOpen, faFolderPlus,
    faFolderMinus, faFile, faFileAlt, faFilePdf, faFileWord, faFileExcel, faFilePowerpoint,
    faFileImage, faFileVideo, faFileAudio, faFileArchive, faFileCode, faFileCsv, faFileInvoice,
    faFileContract, faFilePrescription, faFileMedical, faFileMedicalAlt, faFileSignature,
    faFolderTree, faFileDownload, faFileUpload, faFileImport, faFileExport, faAd, faAddressBook,
    faAddressCard, faAdjust, faAirFreshener, faAlignCenter, faAlignJustify, faAlignLeft, faAlignRight,
    faAllergies, faAmbulance, faAmericanSignLanguageInterpreting, faAnchor, faAngleDoubleDown,
    faAngleDoubleLeft, faAngleDoubleRight, faAngleDoubleUp, faAngry, faAnkh, faAppleAlt, faArchive,
    faArchway, faArrowAltCircleDown, faArrowAltCircleLeft, faArrowAltCircleRight, faArrowAltCircleUp,
    faArrowCircleDown, faArrowCircleLeft, faArrowCircleRight, faArrowCircleUp, faArrowsAlt, faArrowsAltH,
    faArrowsAltV, faAssistiveListeningSystems, faAsterisk, faAt, faAtlas, faAtom, faAudioDescription,
    faAward, faGasPump, faGauge, faGaugeHigh, faGaugeSimple, faGaugeSimpleHigh, faGavel, faGear, faGears,
    faGem, faGenderless, faGhost, faGift, faGifts, faGlassCheers, faGlassMartini, faGlassMartiniAlt,
    faGlassWhiskey, faGlasses, faGlobeAfrica, faGlobeAmericas, faGlobeAsia, faGlobeEurope,
    faGolfBall, faGopuram, faGraduationCap, faGreaterThan, faGreaterThanEqual, faGrip, faGripHorizontal,
    faGripLines, faGripLinesVertical, faGripVertical, faGroupArrowsRotate, faGuaraniSign, faGuitar,
    faGun, faHammer, faHamsa, faHand, faHandBackFist, faHandDots, faHandFist, faHandHolding, faHandHoldingDollar,
    faHandHoldingDroplet, faHandHoldingHeart, faHandHoldingMedical, faHandLizard, faHandMiddleFinger,
    faHandPeace, faHandPointDown, faHandPointLeft, faHandPointRight, faHandPointUp, faHandPointer,
    faHandScissors, faHandSparkles, faHandSpock, faHandcuffs, faHands, faHandsAslInterpreting, faHandsBound,
    faHandsBubbles, faHandsClapping, faHandsHolding, faHandsHoldingChild, faHandsHoldingCircle,
    faHandsPraying, faHandshake, faHandshakeAngle, faHandshakeSimple, faHandshakeSimpleSlash,
    faHandshakeSlash, faHanukiah, faHardDrive, faHashtag, faHatCowboy, faHatCowboySide, faHatWizard,
    faHeadSideCough, faHeadSideCoughSlash, faHeadSideMask, faHeadSideVirus, faHeading,
    faHeadphonesSimple, faHeadset, faHeartCircleBolt, faHeartCircleCheck, faHeartCircleExclamation,
    faHeartCircleMinus, faHeartCirclePlus, faHeartCircleXmark, faHeartCrack, faHeartPulse, faHelicopter,
    faHelicopterSymbol, faHelmetSafety, faHelmetUn, faHillAvalanche, faHillRockslide, faHippo,
    faHockeyPuck, faHollyBerry, faHorse, faHorseHead, faHospital, faHospitalUser, faHotTubPerson, faHotdog,
    faHotel, faHourglass, faHourglassEmpty, faHourglassEnd, faHourglassHalf, faHourglassStart, faHouse,
    faHouseChimney, faHouseChimneyCrack, faHouseChimneyMedical, faHouseChimneyUser, faHouseChimneyWindow,
    faHouseCircleCheck, faHouseCircleExclamation, faHouseCircleXmark, faHouseCrack, faHouseFire, faHouseFlag,
    faHouseFloodWater, faHouseFloodWaterCircleArrowRight, faHouseLaptop, faHouseLock, faHouseMedical,
    faHouseMedicalCircleCheck, faHouseMedicalCircleExclamation, faHouseMedicalCircleXmark, faHouseMedicalFlag,
    faHouseSignal, faHouseTsunami, faHouseUser, faHryvniaSign, faHurricane, faJar, faJarWheat, faJedi,
    faJetFighter, faJetFighterUp, faJoint, faJugDetergent, faLandMineOn, faLandmark, faLandmarkAlt,
    faLanguage, faLaptopCode, faLaptopHouse, faLaptopMedical, faLariSign, faLayerGroup, faLeaf, faLeftLong,
    faLeftRight, faLemon, faLessThan, faLessThanEqual, faLifeRing, faLightbulb, faLink, faLinkSlash,
    faLiraSign, faListAlt, faListOl, faListUl, faLitecoinSign, faLocationArrow, faLocationCrosshairs,
    faLocationDot, faLocationPin, faLockOpen, faLocust, faLongArrowAltDown, faLongArrowAltLeft,
    faLongArrowAltRight, faLongArrowAltUp, faLowVision, faLuggageCart, faM, faMagnet, faMagnifyingGlass,
    faMagnifyingGlassArrowRight, faMagnifyingGlassChart, faMagnifyingGlassDollar, faMagnifyingGlassLocation,
    faMagnifyingGlassMinus, faMagnifyingGlassPlus, faManatSign, faMapLocation, faMapLocationDot, faMarker,
    faMars, faMarsAndVenus, faMarsAndVenusBurst, faMarsDouble, faMarsStroke, faMarsStrokeRight, faMarsStrokeUp,
    faMartiniGlass, faMartiniGlassCitrus, faMartiniGlassEmpty, faMask, faMaskFace, faMaskVentilator,
    faMasksTheater, faMattressPillow, faMaximize, faMedal, faMemory, faMenorah, faMercury, faMessage, faMeteor,
    faMicrochip, faMicrophoneAlt, faMicrophoneLines, faMicrophoneLinesSlash, faMicroscope, faMillSign, faMinimize,
    faMinusCircle, faMinusSquare, faMitten, faMobileAlt, faMobileButton, faMobileRetro, faMobileScreen,
    faMobileScreenButton, faMoneyBill, faMoneyBill1, faMoneyBillAlt, faMoneyBillWave, faMoneyBillTransfer,
    faMoneyBillTrendUp, faMoneyBillWaveAlt, faMoneyBillWheat, faMoneyBills, faMoneyCheck, faMoneyCheckAlt,
    faMonument, faMoon, faMortarPestle, faMosque, faMosquito, faMosquitoNet, faMotorcycle, faMound, faMountain,
    faMountainCity, faMountainSun, faMugHot, faMugSaucer,
    faNairaSign, faNetworkWired, faNeuter, faNewspaper, faNotEqual, faNotdef, faNoteSticky, faNotesMedical,
    faObjectGroup, faObjectUngroup, faOilCan, faOm, faOtter, faOutdent, faP, faPager, faPallet, faPanorama,
    faPaperPlane, faPaperclip, faParachuteBox, faParagraph, faPassport, faPaw, faPeace, faPenClip, faPenFancy,
    faPenRuler, faPeopleArrowsLeftRight, faPeopleCarry, faPepperHot, faPercent, faPercentage, faPerson,
    faPersonArrowDownToLine, faPersonArrowUpFromLine, faPersonBiking, faPersonBooth, faPersonCane,
    faPersonCircleCheck, faPersonCircleExclamation, faPersonCircleMinus, faPersonCirclePlus, faPersonCircleQuestion,
    faPersonCircleXmark, faPersonDotsFromLine, faPersonDress, faPersonDressBurst, faPersonDrowning, faPersonFalling,
    faPersonFallingBurst, faPersonHalfDress, faPersonHarassing, faPersonHiking, faPersonMilitaryPointing,
    faPersonMilitaryRifle, faPersonMilitaryToPerson, faPersonPraying, faPersonPregnant, faPersonRays, faPersonRifle,
    faPersonRunning, faPersonShelter, faPersonSkating, faPersonSkiing, faPersonSkiingNordic, faPersonSnowboarding,
    faPersonSwimming, faPersonThroughWindow, faPersonWalking, faPersonWalkingArrowLoopLeft, faPersonWalkingArrowRight,
    faPersonWalkingDashedLineArrowRight, faPersonWalkingLuggage, faPersonWalkingWithCane, faPhoneAlt, faPhoneFlip,
    faPhoneSlash, faPhoneSquareAlt, faPhoneVolume, faPhotoFilm, faPiggyBank, faPills, faPizzaSlice, faPlaceOfWorship,
    faPlane, faPlaneArrival, faPlaneCircleCheck, faPlaneCircleExclamation, faPlaneCircleXmark, faPlaneDeparture,
    faPlaneLock, faPlaneSlash, faPlaneUp, faPlantWilt, faPlateWheat, faPlayCircle, faPlug, faPlugCircleBolt,
    faPlugCircleCheck, faPlugCircleExclamation, faPlugCircleMinus, faPlugCirclePlus, faPlugCircleXmark, faPlusCircle,
    faPlusMinus, faPodcast, faPoo, faPooStorm, faPoop, faPowerOff, faPrescription, faPrescriptionBottle,
    faPrescriptionBottleAlt, faPrescriptionBottleMedical, faPumpMedical, faPumpSoap, faPuzzlePiece, faQ, faQrcode,
    faQuestion, faQuidditch, faQuoteLeft, faQuoteRight, faQuran, faRadiation, faRainbow, faRankingStar, faReceipt,
    faRecordVinyl, faRectangleAd, faRectangleList, faRectangleXmark, faRecycle, faRegistered, faRepeat, faReply,
    faReplyAll, faRepublican, faRestroom, faRetweet, faRibbon, faRightFromBracket, faRightLeft, faRightLong,
    faRightToBracket, faRing, faRoad, faRoadBarrier, faRoadBridge, faRoadCircleCheck, faRoadCircleExclamation,
    faRoadCircleXmark, faRoadLock, faRoadSpikes, faRobot, faRocket, faRotate, faRotateLeft, faRotateRight, faRoute,
    faRss, faRubleSign, faRupeeSign, faRupiahSign, faSackDollar, faSackXmark, faSailboat, faSatellite, faSatelliteDish,
    faScaleBalanced, faScaleUnbalanced, faScaleUnbalancedFlip, faSchool, faSchoolCircleCheck, faSchoolCircleExclamation,
    faSchoolCircleXmark, faSchoolFlag, faSchoolLock, faScissors, faScrewdriver, faScrewdriverWrench, faScroll, faScrollTorah,
    faSdCard, faSection, faSeedling, faServer, faShapes, faShareAlt, faShield, faShieldCat, faShieldDog, faShieldHalved,
    faShieldHeart, faShieldVirus, faShip, faShirt, faShoePrints, faShop, faShopLock, faShopSlash, faShower, faShrimp, faShuffle,
    faShuttleSpace, faSignHanging, faSignal, faSignature, faSignsPost, faSimCard, faSink, faSitemap, faSkull, faSkullCrossbones,
    faSlash, faSleigh, faSliders, faSmog, faSmoking, faSnowflake, faSnowman, faSnowplow, faSoap, faSocks, faSolarPanel, faSort,
    faSortDown, faSortUp, faSpa, faSpaghettiMonsterFlying, faSpellCheck, faSpider, faSplotch, faSpoon, faSprayCanSparkles,
    faSquareArrowUpRight, faSquareCaretDown, faSquareCaretLeft, faSquareCaretRight, faSquareCaretUp, faSquareCheck, faSquareEnvelope,
    faSquareFull, faSquareH, faSquareMinus, faSquareNfi, faSquareParking, faSquarePen, faSquarePersonConfined, faSquarePhone,
    faSquarePhoneFlip, faSquarePlus, faSquarePollHorizontal, faSquarePollVertical, faSquareRootVariable, faSquareRss,
    faSquareShareNodes, faSquareUpRight, faSquareVirus, faSquareXmark, faStaffSnake, faStairs, faStarAndCrescent, faStarHalf,
    faStarHalfStroke, faStarOfDavid, faStarOfLife, faSterlingSign, faStethoscope, faStopwatch, faStopwatch20, faStore, faStoreSlash,
    faStreetView, faStrikethrough, faStroopwafel, faSubscript, faSuitcase, faSuitcaseMedical, faSuitcaseRolling, faSun,
    faSunPlantWilt, faSuperscript, faSwatchbook, faSynagogue, faSyringe, faT, faTableCells, faTableCellsLarge, faTableColumns,
    faTableList, faTableTennisPaddleBall, faTabletButton, faTabletScreenButton, faTablets, faTachographDigital, faTarp, faTarpDroplet,
    faTaxi, faTabletAlt, faTanakh, faTape, faTeeth, faTeethOpen, faTemperatureArrowDown, faTemperatureArrowUp, faTemperatureEmpty,
    faTemperatureFull, faTemperatureHalf, faTemperatureHigh, faTemperatureLow, faTemperatureQuarter, faTemperatureThreeQuarters,
    faTengeSign, faTent, faTentArrowDownToLine, faTentArrowLeftRight, faTentArrowTurnLeft, faTentArrowsDown, faTents, faTerminal,
    faTextHeight, faTextSlash, faTextWidth, faTheaterMasks, faThermometer, faThumbtack, faTicket, faTicketAlt, faTicketSimple,
    faTimeline, faTimes, faTimesRectangle, faTint, faTintSlash, faTired, faToggleOff, faToggleOn, faToilet, faToiletPaper,
    faToiletPaperSlash, faToiletPortable, faToiletsPortable, faToolbox, faTools, faTooth, faTorah, faToriiGate, faTornado,
    faTowerBroadcast, faTowerCell, faTractor, faTrademark, faTrafficLight, faTrailer, faTrain, faTrainSubway, faTram, faTransgender,
    faTransgenderAlt, faTrashArrowUp, faTrashAlt, faTrashCan, faTrashCanArrowUp, faTree, faTreeCity, faTriangleCircleSquare,
    faTriangleExclamation, faTrophy, faTrowel, faTrowelBricks, faTruck, faTruckArrowRight, faTruckDroplet, faTruckFast, faTruckField,
    faTruckFieldUn, faTruckFront, faTruckMedical, faTruckMonster, faTruckMoving, faTruckPickup, faTruckPlane, faTruckRampBox,
    faTty, faTurkishLiraSign, faTurnDown, faTurnUp, faTv, faTvAlt, faUmbrella, faUmbrellaBeach, faUnderline, faUndo, faUndoAlt,
    faUniversalAccess, faUnlockAlt, faUpDown, faUpDownLeftRight, faUpLong, faUpRightAndDownLeftFromCenter, faUpRightFromSquare,
    faUserAlt, faUserAltSlash, faUserAstronaut, faUserCheck, faUserCircle, faUserClock, faUserCog, faUserDoctor, faUserEdit,
    faUserFriends, faUserGear, faUserGraduate, faUserInjured, faUserLarge, faUserLargeSlash, faUserLock, faUserMd, faUserMinus,
    faUserNinja, faUserNurse, faUserPen, faUserPlus, faUserSecret, faUserShield, faUserSlash, faUserTag, faUserTie, faUserXmark,
    faUsers, faUsersBetweenLines, faUsersCog, faUsersGear, faUsersLine, faUsersRays, faUsersRectangle, faUsersSlash, faUsersViewfinder,
    faUtensilSpoon, faUtensils, faV, faVanShuttle, faVault, faVectorSquare, faVenus, faVenusDouble,
    faVenusMars, faVest, faVestPatches, faVial, faVialCircleCheck, faVialVirus, faVials, faVideoSlash, faVihara, faVirus,
    faVirusCovid, faVirusCovidSlash, faVirusSlash, faVoicemail, faVolcano, faVolumeXmark, faVrCardboard, faWandMagic,
    faWandMagicSparkles, faWandSparkles, faWarehouse, faWater, faWaterLadder, faWaveSquare, faWeightHanging, faWeightScale,
    faWheelchair, faWhiskeyGlass, faWifi, faWind, faWineBottle, faWineGlass, faWineGlassAlt, faWonSign, faWorm, faX,
    faXRay, faXmark, faXmarksLines, faYenSign, faYinYang
} from '@fortawesome/free-solid-svg-icons';

export const iconsMap = {
    Box: faBox,
    Coffee: faCoffee,
    CheckCircle: faCheckCircle,
    TimesCircle: faTimesCircle,
    User: faUser,
    Home: faHome,
    Search: faSearch,
    Bell: faBell,
    Envelope: faEnvelope,
    AngleRight: faAngleRight,
    AngleLeft: faAngleLeft,
    ArrowUp: faArrowUp,
    ArrowDown: faArrowDown,
    ArrowLeft: faArrowLeft,
    ArrowRight: faArrowRight,
    CaretUp: faCaretUp,
    CaretDown: faCaretDown,
    CaretLeft: faCaretLeft,
    CaretRight: faCaretRight,
    Edit: faEdit,
    Trash: faTrash,
    Save: faSave,
    Download: faDownload,
    Upload: faUpload,
    Plus: faPlus,
    Minus: faMinus,
    ExclamationCircle: faExclamationCircle,
    InfoCircle: faInfoCircle,
    QuestionCircle: faQuestionCircle,
    Star: faStar,
    Heart: faHeart,
    ThumbsUp: faThumbsUp,
    ThumbsDown: faThumbsDown,
    Comment: faComment,
    Share: faShare,
    Eye: faEye,
    EyeSlash: faEyeSlash,
    Lock: faLock,
    Unlock: faUnlock,
    Print: faPrint,
    SignInAlt: faSignInAlt,
    SignOutAlt: faSignOutAlt,
    Sync: faSync,
    Cog: faCog,
    Wrench: faWrench,
    List: faList,
    Table: faTable,
    ChartBar: faChartBar,
    ChartPie: faChartPie,
    ChartLine: faChartLine,
    Map: faMap,
    MapMarker: faMapMarker,
    MapPin: faMapPin,
    Globe: faGlobe,
    Clock: faClock,
    Calendar: faCalendar,
    EnvelopeOpen: faEnvelopeOpen,
    EnvelopeSquare: faEnvelopeSquare,
    Phone: faPhone,
    PhoneSquare: faPhoneSquare,
    Mobile: faMobile,
    Tablet: faTablet,
    Laptop: faLaptop,
    Desktop: faDesktop,
    Headphones: faHeadphones,
    VolumeUp: faVolumeUp,
    VolumeDown: faVolumeDown,
    VolumeMute: faVolumeMute,
    Music: faMusic,
    Video: faVideo,
    Camera: faCamera,
    Microphone: faMicrophone,
    MicrophoneSlash: faMicrophoneSlash,
    Play: faPlay,
    Pause: faPause,
    Stop: faStop,
    Forward: faForward,
    Backward: faBackward,
    FastForward: faFastForward,
    FastBackward: faFastBackward,
    StepForward: faStepForward,
    StepBackward: faStepBackward,
    Circle: faCircle,
    Square: faSquare,
    CheckSquare: faCheckSquare,
    TimesSquare: faTimesSquare,
    ChevronUp: faChevronUp,
    ChevronDown: faChevronDown,
    ChevronLeft: faChevronLeft,
    ChevronRight: faChevronRight,
    Bars: faBars,
    Th: faTh,
    ThLarge: faThLarge,
    ThList: faThList,
    Spinner: faSpinner,
    EllipsisH: faEllipsisH,
    EllipsisV: faEllipsisV,
    CaretSquareUp: faCaretSquareUp,
    CaretSquareDown: faCaretSquareDown,
    CaretSquareLeft: faCaretSquareLeft,
    CaretSquareRight: faCaretSquareRight,
    Pen: faPen,
    PenAlt: faPenAlt,
    PenSquare: faPenSquare,
    PenNib: faPenNib,
    Highlighter: faHighlighter,
    Pencil: faPencil,
    PencilAlt: faPencilAlt,
    PencilSquare: faPencilSquare,
    PencilRuler: faPencilRuler,
    Ruler: faRuler,
    RulerCombined: faRulerCombined,
    RulerHorizontal: faRulerHorizontal,
    RulerVertical: faRulerVertical,
    DraftingCompass: faDraftingCompass,
    Compass: faCompass,
    PaintBrush: faPaintBrush,
    PaintRoller: faPaintRoller,
    Palette: faPalette,
    Brush: faBrush,
    SprayCan: faSprayCan,
    Eraser: faEraser,
    Stamp: faStamp,
    Cut: faCut,
    Copy: faCopy,
    Paste: faPaste,
    Clipboard: faClipboard,
    ClipboardCheck: faClipboardCheck,
    ClipboardList: faClipboardList,
    ClipboardUser: faClipboardUser,
    StickyNote: faStickyNote,
    Tag: faTag,
    Tags: faTags,
    Book: faBook,
    Bookmark: faBookmark,
    Folder: faFolder,
    FolderOpen: faFolderOpen,
    FolderPlus: faFolderPlus,
    FolderMinus: faFolderMinus,
    File: faFile,
    FileAlt: faFileAlt,
    FilePdf: faFilePdf,
    FileWord: faFileWord,
    FileExcel: faFileExcel,
    FilePowerpoint: faFilePowerpoint,
    FileImage: faFileImage,
    FileVideo: faFileVideo,
    FileAudio: faFileAudio,
    FileArchive: faFileArchive,
    FileCode: faFileCode,
    FileCsv: faFileCsv,
    FileInvoice: faFileInvoice,
    FileContract: faFileContract,
    FilePrescription: faFilePrescription,
    FileMedical: faFileMedical,
    FileMedicalAlt: faFileMedicalAlt,
    FileSignature: faFileSignature,
    FolderTree: faFolderTree,
    FileDownload: faFileDownload,
    FileUpload: faFileUpload,
    FileImport: faFileImport,
    FileExport: faFileExport,
    Ad: faAd,
    AddressBook: faAddressBook,
    AddressCard: faAddressCard,
    Adjust: faAdjust,
    AirFreshener: faAirFreshener,
    AlignCenter: faAlignCenter,
    AlignJustify: faAlignJustify,
    AlignLeft: faAlignLeft,
    AlignRight: faAlignRight,
    Allergies: faAllergies,
    Ambulance: faAmbulance,
    AmericanSignLanguageInterpreting: faAmericanSignLanguageInterpreting,
    Anchor: faAnchor,
    AngleDoubleDown: faAngleDoubleDown,
    AngleDoubleLeft: faAngleDoubleLeft,
    AngleDoubleRight: faAngleDoubleRight,
    AngleDoubleUp: faAngleDoubleUp,
    Angry: faAngry,
    Ankh: faAnkh,
    AppleAlt: faAppleAlt,
    Archive: faArchive,
    Archway: faArchway,
    ArrowAltCircleDown: faArrowAltCircleDown,
    ArrowAltCircleLeft: faArrowAltCircleLeft,
    ArrowAltCircleRight: faArrowAltCircleRight,
    ArrowAltCircleUp: faArrowAltCircleUp,
    ArrowCircleDown: faArrowCircleDown,
    ArrowCircleLeft: faArrowCircleLeft,
    ArrowCircleRight: faArrowCircleRight,
    ArrowCircleUp: faArrowCircleUp,
    ArrowsAlt: faArrowsAlt,
    ArrowsAltH: faArrowsAltH,
    ArrowsAltV: faArrowsAltV,
    AssistiveListeningSystems: faAssistiveListeningSystems,
    Asterisk: faAsterisk,
    At: faAt,
    Atlas: faAtlas,
    Atom: faAtom,
    AudioDescription: faAudioDescription,
    Award: faAward,
    GasPump: faGasPump,
    Gauge: faGauge,
    GaugeHigh: faGaugeHigh,
    GaugeSimple: faGaugeSimple,
    GaugeSimpleHigh: faGaugeSimpleHigh,
    Gavel: faGavel,
    Gear: faGear,
    Gears: faGears,
    Gem: faGem,
    Genderless: faGenderless,
    Ghost: faGhost,
    Gift: faGift,
    Gifts: faGifts,
    GlassCheers: faGlassCheers,
    GlassMartini: faGlassMartini,
    GlassMartiniAlt: faGlassMartiniAlt,
    GlassWhiskey: faGlassWhiskey,
    Glasses: faGlasses,
    GlobeAfrica: faGlobeAfrica,
    GlobeAmericas: faGlobeAmericas,
    GlobeAsia: faGlobeAsia,
    GlobeEurope: faGlobeEurope,
    GolfBall: faGolfBall,
    Gopuram: faGopuram,
    GraduationCap: faGraduationCap,
    GreaterThan: faGreaterThan,
    GreaterThanEqual: faGreaterThanEqual,
    Grip: faGrip,
    GripHorizontal: faGripHorizontal,
    GripLines: faGripLines,
    GripLinesVertical: faGripLinesVertical,
    GripVertical: faGripVertical,
    GroupArrowsRotate: faGroupArrowsRotate,
    GuaraniSign: faGuaraniSign,
    Guitar: faGuitar,
    Gun: faGun,
    Hammer: faHammer,
    Hamsa: faHamsa,
    Hand: faHand,
    HandBackFist: faHandBackFist,
    HandDots: faHandDots,
    HandFist: faHandFist,
    HandHolding: faHandHolding,
    HandHoldingDollar: faHandHoldingDollar,
    HandHoldingDroplet: faHandHoldingDroplet,
    HandHoldingHeart: faHandHoldingHeart,
    HandHoldingMedical: faHandHoldingMedical,
    HandLizard: faHandLizard,
    HandMiddleFinger: faHandMiddleFinger,
    HandPeace: faHandPeace,
    HandPointDown: faHandPointDown,
    HandPointLeft: faHandPointLeft,
    HandPointRight: faHandPointRight,
    HandPointUp: faHandPointUp,
    HandPointer: faHandPointer,
    HandScissors: faHandScissors,
    HandSparkles: faHandSparkles,
    HandSpock: faHandSpock,
    Handcuffs: faHandcuffs,
    Hands: faHands,
    HandsAslInterpreting: faHandsAslInterpreting,
    HandsBound: faHandsBound,
    HandsBubbles: faHandsBubbles,
    HandsClapping: faHandsClapping,
    HandsHolding: faHandsHolding,
    HandsHoldingChild: faHandsHoldingChild,
    HandsHoldingCircle: faHandsHoldingCircle,
    HandsPraying: faHandsPraying,
    Handshake: faHandshake,
    HandshakeAngle: faHandshakeAngle,
    HandshakeSimple: faHandshakeSimple,
    HandshakeSimpleSlash: faHandshakeSimpleSlash,
    HandshakeSlash: faHandshakeSlash,
    Hanukiah: faHanukiah,
    HardDrive: faHardDrive,
    Hashtag: faHashtag,
    HatCowboy: faHatCowboy,
    HatCowboySide: faHatCowboySide,
    HatWizard: faHatWizard,
    HeadSideCough: faHeadSideCough,
    HeadSideCoughSlash: faHeadSideCoughSlash,
    HeadSideMask: faHeadSideMask,
    HeadSideVirus: faHeadSideVirus,
    Heading: faHeading,
    HeadphonesSimple: faHeadphonesSimple,
    Headset: faHeadset,
    HeartCircleBolt: faHeartCircleBolt,
    HeartCircleCheck: faHeartCircleCheck,
    HeartCircleExclamation: faHeartCircleExclamation,
    HeartCircleMinus: faHeartCircleMinus,
    HeartCirclePlus: faHeartCirclePlus,
    HeartCircleXmark: faHeartCircleXmark,
    HeartCrack: faHeartCrack,
    HeartPulse: faHeartPulse,
    Helicopter: faHelicopter,
    HelicopterSymbol: faHelicopterSymbol,
    HelmetSafety: faHelmetSafety,
    HelmetUn: faHelmetUn,
    HillAvalanche: faHillAvalanche,
    HillRockslide: faHillRockslide,
    Hippo: faHippo,
    HockeyPuck: faHockeyPuck,
    HollyBerry: faHollyBerry,
    Horse: faHorse,
    HorseHead: faHorseHead,
    Hospital: faHospital,
    HospitalUser: faHospitalUser,
    HotTubPerson: faHotTubPerson,
    Hotdog: faHotdog,
    Hotel: faHotel,
    Hourglass: faHourglass,
    HourglassEmpty: faHourglassEmpty,
    HourglassEnd: faHourglassEnd,
    HourglassHalf: faHourglassHalf,
    HourglassStart: faHourglassStart,
    House: faHouse,
    HouseChimney: faHouseChimney,
    HouseChimneyCrack: faHouseChimneyCrack,
    HouseChimneyMedical: faHouseChimneyMedical,
    HouseChimneyUser: faHouseChimneyUser,
    HouseChimneyWindow: faHouseChimneyWindow,
    HouseCircleCheck: faHouseCircleCheck,
    HouseCircleExclamation: faHouseCircleExclamation,
    HouseCircleXmark: faHouseCircleXmark,
    HouseCrack: faHouseCrack,
    HouseFire: faHouseFire,
    HouseFlag: faHouseFlag,
    HouseFloodWater: faHouseFloodWater,
    HouseFloodWaterCircleArrowRight: faHouseFloodWaterCircleArrowRight,
    HouseLaptop: faHouseLaptop,
    HouseLock: faHouseLock,
    HouseMedical: faHouseMedical,
    HouseMedicalCircleCheck: faHouseMedicalCircleCheck,
    HouseMedicalCircleExclamation: faHouseMedicalCircleExclamation,
    HouseMedicalCircleXmark: faHouseMedicalCircleXmark,
    HouseMedicalFlag: faHouseMedicalFlag,
    HouseSignal: faHouseSignal,
    HouseTsunami: faHouseTsunami,
    HouseUser: faHouseUser,
    HryvniaSign: faHryvniaSign,
    Hurricane: faHurricane,
    Jar: faJar,
    JarWheat: faJarWheat,
    Jedi: faJedi,
    JetFighter: faJetFighter,
    JetFighterUp: faJetFighterUp,
    Joint: faJoint,
    JugDetergent: faJugDetergent,
    LandMineOn: faLandMineOn,
    Landmark: faLandmark,
    LandmarkAlt: faLandmarkAlt,
    Language: faLanguage,
    LaptopCode: faLaptopCode,
    LaptopHouse: faLaptopHouse,
    LaptopMedical: faLaptopMedical,
    LariSign: faLariSign,
    LayerGroup: faLayerGroup,
    Leaf: faLeaf,
    LeftLong: faLeftLong,
    LeftRight: faLeftRight,
    Lemon: faLemon,
    LessThan: faLessThan,
    LessThanEqual: faLessThanEqual,
    LifeRing: faLifeRing,
    Lightbulb: faLightbulb,
    Link: faLink,
    LinkSlash: faLinkSlash,
    LiraSign: faLiraSign,
    ListAlt: faListAlt,
    ListOl: faListOl,
    ListUl: faListUl,
    LitecoinSign: faLitecoinSign,
    LocationArrow: faLocationArrow,
    LocationCrosshairs: faLocationCrosshairs,
    LocationDot: faLocationDot,
    LocationPin: faLocationPin,
    LockOpen: faLockOpen,
    Locust: faLocust,
    LongArrowAltDown: faLongArrowAltDown,
    LongArrowAltLeft: faLongArrowAltLeft,
    LongArrowAltRight: faLongArrowAltRight,
    LongArrowAltUp: faLongArrowAltUp,
    LowVision: faLowVision,
    LuggageCart: faLuggageCart,
    M: faM,
    Magnet: faMagnet,
    MagnifyingGlass: faMagnifyingGlass,
    MagnifyingGlassArrowRight: faMagnifyingGlassArrowRight,
    MagnifyingGlassChart: faMagnifyingGlassChart,
    MagnifyingGlassDollar: faMagnifyingGlassDollar,
    MagnifyingGlassLocation: faMagnifyingGlassLocation,
    MagnifyingGlassMinus: faMagnifyingGlassMinus,
    MagnifyingGlassPlus: faMagnifyingGlassPlus,
    ManatSign: faManatSign,
    MapLocation: faMapLocation,
    MapLocationDot: faMapLocationDot,
    Marker: faMarker,
    Mars: faMars,
    MarsAndVenus: faMarsAndVenus,
    MarsAndVenusBurst: faMarsAndVenusBurst,
    MarsDouble: faMarsDouble,
    MarsStroke: faMarsStroke,
    MarsStrokeRight: faMarsStrokeRight,
    MarsStrokeUp: faMarsStrokeUp,
    MartiniGlass: faMartiniGlass,
    MartiniGlassCitrus: faMartiniGlassCitrus,
    MartiniGlassEmpty: faMartiniGlassEmpty,
    Mask: faMask,
    MaskFace: faMaskFace,
    MaskVentilator: faMaskVentilator,
    MasksTheater: faMasksTheater,
    MattressPillow: faMattressPillow,
    Maximize: faMaximize,
    Medal: faMedal,
    Memory: faMemory,
    Menorah: faMenorah,
    Mercury: faMercury,
    Message: faMessage,
    Meteor: faMeteor,
    Microchip: faMicrochip,
    MicrophoneAlt: faMicrophoneAlt,
    MicrophoneLines: faMicrophoneLines,
    MicrophoneLinesSlash: faMicrophoneLinesSlash,
    Microscope: faMicroscope,
    MillSign: faMillSign,
    Minimize: faMinimize,
    MinusCircle: faMinusCircle,
    MinusSquare: faMinusSquare,
    Mitten: faMitten,
    MobileAlt: faMobileAlt,
    MobileButton: faMobileButton,
    MobileRetro: faMobileRetro,
    MobileScreen: faMobileScreen,
    MobileScreenButton: faMobileScreenButton,
    MoneyBill: faMoneyBill,
    MoneyBill1: faMoneyBill1,
    MoneyBillAlt: faMoneyBillAlt,
    MoneyBillWave: faMoneyBillWave,
    MoneyBillTransfer: faMoneyBillTransfer,
    MoneyBillTrendUp: faMoneyBillTrendUp,
    MoneyBillWaveAlt: faMoneyBillWaveAlt,
    MoneyBillWheat: faMoneyBillWheat,
    MoneyBills: faMoneyBills,
    MoneyCheck: faMoneyCheck,
    MoneyCheckAlt: faMoneyCheckAlt,
    Monument: faMonument,
    Moon: faMoon,
    MortarPestle: faMortarPestle,
    Mosque: faMosque,
    Mosquito: faMosquito,
    MosquitoNet: faMosquitoNet,
    Motorcycle: faMotorcycle,
    Mound: faMound,
    Mountain: faMountain,
    MountainCity: faMountainCity,
    MountainSun: faMountainSun,
    MugHot: faMugHot,
    MugSaucer: faMugSaucer,
    NairaSign: faNairaSign,
    NetworkWired: faNetworkWired,
    Neuter: faNeuter,
    Newspaper: faNewspaper,
    NotEqual: faNotEqual,
    Notdef: faNotdef,
    NoteSticky: faNoteSticky,
    NotesMedical: faNotesMedical,
    ObjectGroup: faObjectGroup,
    ObjectUngroup: faObjectUngroup,
    OilCan: faOilCan,
    Om: faOm,
    Otter: faOtter,
    Outdent: faOutdent,
    P: faP,
    Pager: faPager,
    Pallet: faPallet,
    Panorama: faPanorama,
    PaperPlane: faPaperPlane,
    Paperclip: faPaperclip,
    ParachuteBox: faParachuteBox,
    Paragraph: faParagraph,
    Passport: faPassport,
    Paw: faPaw,
    Peace: faPeace,
    PenClip: faPenClip,
    PenFancy: faPenFancy,
    PenRuler: faPenRuler,
    PeopleArrowsLeftRight: faPeopleArrowsLeftRight,
    PeopleCarry: faPeopleCarry,
    PepperHot: faPepperHot,
    Percent: faPercent,
    Percentage: faPercentage,
    Person: faPerson,
    PersonArrowDownToLine: faPersonArrowDownToLine,
    PersonArrowUpFromLine: faPersonArrowUpFromLine,
    PersonBiking: faPersonBiking,
    PersonBooth: faPersonBooth,
    PersonCane: faPersonCane,
    PersonCircleCheck: faPersonCircleCheck,
    PersonCircleExclamation: faPersonCircleExclamation,
    PersonCircleMinus: faPersonCircleMinus,
    PersonCirclePlus: faPersonCirclePlus,
    PersonCircleQuestion: faPersonCircleQuestion,
    PersonCircleXmark: faPersonCircleXmark,
    PersonDotsFromLine: faPersonDotsFromLine,
    PersonDress: faPersonDress,
    PersonDressBurst: faPersonDressBurst,
    PersonDrowning: faPersonDrowning,
    PersonFalling: faPersonFalling,
    PersonFallingBurst: faPersonFallingBurst,
    PersonHalfDress: faPersonHalfDress,
    PersonHarassing: faPersonHarassing,
    PersonHiking: faPersonHiking,
    PersonMilitaryPointing: faPersonMilitaryPointing,
    PersonMilitaryRifle: faPersonMilitaryRifle,
    PersonMilitaryToPerson: faPersonMilitaryToPerson,
    PersonPraying: faPersonPraying,
    PersonPregnant: faPersonPregnant,
    PersonRays: faPersonRays,
    PersonRifle: faPersonRifle,
    PersonRunning: faPersonRunning,
    PersonShelter: faPersonShelter,
    PersonSkating: faPersonSkating,
    PersonSkiing: faPersonSkiing,
    PersonSkiingNordic: faPersonSkiingNordic,
    PersonSnowboarding: faPersonSnowboarding,
    PersonSwimming: faPersonSwimming,
    PersonThroughWindow: faPersonThroughWindow,
    PersonWalking: faPersonWalking,
    PersonWalkingArrowLoopLeft: faPersonWalkingArrowLoopLeft,
    PersonWalkingArrowRight: faPersonWalkingArrowRight,
    PersonWalkingDashedLineArrowRight: faPersonWalkingDashedLineArrowRight,
    PersonWalkingLuggage: faPersonWalkingLuggage,
    PersonWalkingWithCane: faPersonWalkingWithCane,
    PhoneAlt: faPhoneAlt,
    PhoneFlip: faPhoneFlip,
    PhoneSlash: faPhoneSlash,
    PhoneSquareAlt: faPhoneSquareAlt,
    PhoneVolume: faPhoneVolume,
    PhotoFilm: faPhotoFilm,
    PiggyBank: faPiggyBank,
    Pills: faPills,
    PizzaSlice: faPizzaSlice,
    PlaceOfWorship: faPlaceOfWorship,
    Plane: faPlane,
    PlaneArrival: faPlaneArrival,
    PlaneCircleCheck: faPlaneCircleCheck,
    PlaneCircleExclamation: faPlaneCircleExclamation,
    PlaneCircleXmark: faPlaneCircleXmark,
    PlaneDeparture: faPlaneDeparture,
    PlaneLock: faPlaneLock,
    PlaneSlash: faPlaneSlash,
    PlaneUp: faPlaneUp,
    PlantWilt: faPlantWilt,
    PlateWheat: faPlateWheat,
    PlayCircle: faPlayCircle,
    Plug: faPlug,
    PlugCircleBolt: faPlugCircleBolt,
    PlugCircleCheck: faPlugCircleCheck,
    PlugCircleExclamation: faPlugCircleExclamation,
    PlugCircleMinus: faPlugCircleMinus,
    PlugCirclePlus: faPlugCirclePlus,
    PlugCircleXmark: faPlugCircleXmark,
    PlusCircle: faPlusCircle,
    PlusMinus: faPlusMinus,
    Podcast: faPodcast,
    Poo: faPoo,
    PooStorm: faPooStorm,
    Poop: faPoop,
    PowerOff: faPowerOff,
    Prescription: faPrescription,
    PrescriptionBottle: faPrescriptionBottle,
    PrescriptionBottleAlt: faPrescriptionBottleAlt,
    PrescriptionBottleMedical: faPrescriptionBottleMedical,
    PumpMedical: faPumpMedical,
    PumpSoap: faPumpSoap,
    PuzzlePiece: faPuzzlePiece,
    Q: faQ,
    Qrcode: faQrcode,
    Question: faQuestion,
    Quidditch: faQuidditch,
    QuoteLeft: faQuoteLeft,
    QuoteRight: faQuoteRight,
    Quran: faQuran,
    Radiation: faRadiation,
    Rainbow: faRainbow,
    RankingStar: faRankingStar,
    Receipt: faReceipt,
    RecordVinyl: faRecordVinyl,
    RectangleAd: faRectangleAd,
    RectangleList: faRectangleList,
    RectangleXmark: faRectangleXmark,
    Recycle: faRecycle,
    Registered: faRegistered,
    Repeat: faRepeat,
    Reply: faReply,
    ReplyAll: faReplyAll,
    Republican: faRepublican,
    Restroom: faRestroom,
    Retweet: faRetweet,
    Ribbon: faRibbon,
    RightFromBracket: faRightFromBracket,
    RightLeft: faRightLeft,
    RightLong: faRightLong,
    RightToBracket: faRightToBracket,
    Ring: faRing,
    Road: faRoad,
    RoadBarrier: faRoadBarrier,
    RoadBridge: faRoadBridge,
    RoadCircleCheck: faRoadCircleCheck,
    RoadCircleExclamation: faRoadCircleExclamation,
    RoadCircleXmark: faRoadCircleXmark,
    RoadLock: faRoadLock,
    RoadSpikes: faRoadSpikes,
    Robot: faRobot,
    Rocket: faRocket,
    Rotate: faRotate,
    RotateLeft: faRotateLeft,
    RotateRight: faRotateRight,
    Route: faRoute,
    Rss: faRss,
    RubleSign: faRubleSign,
    RupeeSign: faRupeeSign,
    RupiahSign: faRupiahSign,
    SackDollar: faSackDollar,
    SackXmark: faSackXmark,
    Sailboat: faSailboat,
    Satellite: faSatellite,
    SatelliteDish: faSatelliteDish,
    ScaleBalanced: faScaleBalanced,
    ScaleUnbalanced: faScaleUnbalanced,
    ScaleUnbalancedFlip: faScaleUnbalancedFlip,
    School: faSchool,
    SchoolCircleCheck: faSchoolCircleCheck,
    SchoolCircleExclamation: faSchoolCircleExclamation,
    SchoolCircleXmark: faSchoolCircleXmark,
    SchoolFlag: faSchoolFlag,
    SchoolLock: faSchoolLock,
    Scissors: faScissors,
    Screwdriver: faScrewdriver,
    ScrewdriverWrench: faScrewdriverWrench,
    Scroll: faScroll,
    ScrollTorah: faScrollTorah,
    SdCard: faSdCard,
    Section: faSection,
    Seedling: faSeedling,
    Server: faServer,
    Shapes: faShapes,
    ShareAlt: faShareAlt,
    Shield: faShield,
    ShieldCat: faShieldCat,
    ShieldDog: faShieldDog,
    ShieldHalved: faShieldHalved,
    ShieldHeart: faShieldHeart,
    ShieldVirus: faShieldVirus,
    Ship: faShip,
    Shirt: faShirt,
    ShoePrints: faShoePrints,
    Shop: faShop,
    ShopLock: faShopLock,
    ShopSlash: faShopSlash,
    Shower: faShower,
    Shrimp: faShrimp,
    Shuffle: faShuffle,
    ShuttleSpace: faShuttleSpace,
    SignHanging: faSignHanging,
    Signal: faSignal,
    Signature: faSignature,
    SignsPost: faSignsPost,
    SimCard: faSimCard,
    Sink: faSink,
    Sitemap: faSitemap,
    Skull: faSkull,
    SkullCrossbones: faSkullCrossbones,
    Slash: faSlash,
    Sleigh: faSleigh,
    Sliders: faSliders,
    Smog: faSmog,
    Smoking: faSmoking,
    Snowflake: faSnowflake,
    Snowman: faSnowman,
    Snowplow: faSnowplow,
    Soap: faSoap,
    Socks: faSocks,
    SolarPanel: faSolarPanel,
    Sort: faSort,
    SortDown: faSortDown,
    SortUp: faSortUp,
    Spa: faSpa,
    SpaghettiMonsterFlying: faSpaghettiMonsterFlying,
    SpellCheck: faSpellCheck,
    Spider: faSpider,
    Splotch: faSplotch,
    Spoon: faSpoon,
    SprayCanSparkles: faSprayCanSparkles,
    SquareArrowUpRight: faSquareArrowUpRight,
    SquareCaretDown: faSquareCaretDown,
    SquareCaretLeft: faSquareCaretLeft,
    SquareCaretRight: faSquareCaretRight,
    SquareCaretUp: faSquareCaretUp,
    SquareCheck: faSquareCheck,
    SquareEnvelope: faSquareEnvelope,
    SquareFull: faSquareFull,
    SquareH: faSquareH,
    SquareMinus: faSquareMinus,
    SquareNfi: faSquareNfi,
    SquareParking: faSquareParking,
    SquarePen: faSquarePen,
    SquarePersonConfined: faSquarePersonConfined,
    SquarePhone: faSquarePhone,
    SquarePhoneFlip: faSquarePhoneFlip,
    SquarePlus: faSquarePlus,
    SquarePollHorizontal: faSquarePollHorizontal,
    SquarePollVertical: faSquarePollVertical,
    SquareRootVariable: faSquareRootVariable,
    SquareRss: faSquareRss,
    SquareShareNodes: faSquareShareNodes,
    SquareUpRight: faSquareUpRight,
    SquareVirus: faSquareVirus,
    SquareXmark: faSquareXmark,
    StaffSnake: faStaffSnake,
    Stairs: faStairs,
    StarAndCrescent: faStarAndCrescent,
    StarHalf: faStarHalf,
    StarHalfStroke: faStarHalfStroke,
    StarOfDavid: faStarOfDavid,
    StarOfLife: faStarOfLife,
    SterlingSign: faSterlingSign,
    Stethoscope: faStethoscope,
    Stopwatch: faStopwatch,
    Stopwatch20: faStopwatch20,
    Store: faStore,
    StoreSlash: faStoreSlash,
    StreetView: faStreetView,
    Strikethrough: faStrikethrough,
    Stroopwafel: faStroopwafel,
    Subscript: faSubscript,
    Suitcase: faSuitcase,
    SuitcaseMedical: faSuitcaseMedical,
    SuitcaseRolling: faSuitcaseRolling,
    Sun: faSun,
    SunPlantWilt: faSunPlantWilt,
    Superscript: faSuperscript,
    Swatchbook: faSwatchbook,
    Synagogue: faSynagogue,
    Syringe: faSyringe,
    T: faT,
    TableCells: faTableCells,
    TableCellsLarge: faTableCellsLarge,
    TableColumns: faTableColumns,
    TableList: faTableList,
    TableTennisPaddleBall: faTableTennisPaddleBall,
    TabletButton: faTabletButton,
    TabletScreenButton: faTabletScreenButton,
    Tablets: faTablets,
    TachographDigital: faTachographDigital,
    Tarp: faTarp,
    TarpDroplet: faTarpDroplet,
    Taxi: faTaxi,
    TabletAlt: faTabletAlt,
    Tanakh: faTanakh,
    Tape: faTape,
    Teeth: faTeeth,
    TeethOpen: faTeethOpen,
    TemperatureArrowDown: faTemperatureArrowDown,
    TemperatureArrowUp: faTemperatureArrowUp,
    TemperatureEmpty: faTemperatureEmpty,
    TemperatureFull: faTemperatureFull,
    TemperatureHalf: faTemperatureHalf,
    TemperatureHigh: faTemperatureHigh,
    TemperatureLow: faTemperatureLow,
    TemperatureQuarter: faTemperatureQuarter,
    TemperatureThreeQuarters: faTemperatureThreeQuarters,
    TengeSign: faTengeSign,
    Tent: faTent,
    TentArrowDownToLine: faTentArrowDownToLine,
    TentArrowLeftRight: faTentArrowLeftRight,
    TentArrowTurnLeft: faTentArrowTurnLeft,
    TentArrowsDown: faTentArrowsDown,
    Tents: faTents,
    Terminal: faTerminal,
    TextHeight: faTextHeight,
    TextSlash: faTextSlash,
    TextWidth: faTextWidth,
    TheaterMasks: faTheaterMasks,
    Thermometer: faThermometer,
    Thumbtack: faThumbtack,
    Ticket: faTicket,
    TicketAlt: faTicketAlt,
    TicketSimple: faTicketSimple,
    Timeline: faTimeline,
    Times: faTimes,
    TimesRectangle: faTimesRectangle,
    Tint: faTint,
    TintSlash: faTintSlash,
    Tired: faTired,
    ToggleOff: faToggleOff,
    ToggleOn: faToggleOn,
    Toilet: faToilet,
    ToiletPaper: faToiletPaper,
    ToiletPaperSlash: faToiletPaperSlash,
    ToiletPortable: faToiletPortable,
    ToiletsPortable: faToiletsPortable,
    Toolbox: faToolbox,
    Tools: faTools,
    Tooth: faTooth,
    Torah: faTorah,
    ToriiGate: faToriiGate,
    Tornado: faTornado,
    TowerBroadcast: faTowerBroadcast,
    TowerCell: faTowerCell,
    Tractor: faTractor,
    Trademark: faTrademark,
    TrafficLight: faTrafficLight,
    Trailer: faTrailer,
    Train: faTrain,
    TrainSubway: faTrainSubway,
    Tram: faTram,
    Transgender: faTransgender,
    TransgenderAlt: faTransgenderAlt,
    TrashArrowUp: faTrashArrowUp,
    TrashAlt: faTrashAlt,
    TrashCan: faTrashCan,
    TrashCanArrowUp: faTrashCanArrowUp,
    Tree: faTree,
    TreeCity: faTreeCity,
    TriangleCircleSquare: faTriangleCircleSquare,
    TriangleExclamation: faTriangleExclamation,
    Trophy: faTrophy,
    Trowel: faTrowel,
    TrowelBricks: faTrowelBricks,
    Truck: faTruck,
    TruckArrowRight: faTruckArrowRight,
    TruckDroplet: faTruckDroplet,
    TruckFast: faTruckFast,
    TruckField: faTruckField,
    TruckFieldUn: faTruckFieldUn,
    TruckFront: faTruckFront,
    TruckMedical: faTruckMedical,
    TruckMonster: faTruckMonster,
    TruckMoving: faTruckMoving,
    TruckPickup: faTruckPickup,
    TruckPlane: faTruckPlane,
    TruckRampBox: faTruckRampBox,
    Tty: faTty,
    TurkishLiraSign: faTurkishLiraSign,
    TurnDown: faTurnDown,
    TurnUp: faTurnUp,
    Tv: faTv,
    TvAlt: faTvAlt,
    Umbrella: faUmbrella,
    UmbrellaBeach: faUmbrellaBeach,
    Underline: faUnderline,
    Undo: faUndo,
    UndoAlt: faUndoAlt,
    UniversalAccess: faUniversalAccess,
    UnlockAlt: faUnlockAlt,
    UpDown: faUpDown,
    UpDownLeftRight: faUpDownLeftRight,
    UpLong: faUpLong,
    UpRightAndDownLeftFromCenter: faUpRightAndDownLeftFromCenter,
    UpRightFromSquare: faUpRightFromSquare,
    UserAlt: faUserAlt,
    UserAltSlash: faUserAltSlash,
    UserAstronaut: faUserAstronaut,
    UserCheck: faUserCheck,
    UserCircle: faUserCircle,
    UserClock: faUserClock,
    UserCog: faUserCog,
    UserDoctor: faUserDoctor,
    UserEdit: faUserEdit,
    UserFriends: faUserFriends,
    UserGear: faUserGear,
    UserGraduate: faUserGraduate,
    UserInjured: faUserInjured,
    UserLarge: faUserLarge,
    UserLargeSlash: faUserLargeSlash,
    UserLock: faUserLock,
    UserMd: faUserMd,
    UserMinus: faUserMinus,
    UserNinja: faUserNinja,
    UserNurse: faUserNurse,
    UserPen: faUserPen,
    UserPlus: faUserPlus,
    UserSecret: faUserSecret,
    UserShield: faUserShield,
    UserSlash: faUserSlash,
    UserTag: faUserTag,
    UserTie: faUserTie,
    UserXmark: faUserXmark,
    Users: faUsers,
    UsersBetweenLines: faUsersBetweenLines,
    UsersCog: faUsersCog,
    UsersGear: faUsersGear,
    UsersLine: faUsersLine,
    UsersRays: faUsersRays,
    UsersRectangle: faUsersRectangle,
    UsersSlash: faUsersSlash,
    UsersViewfinder: faUsersViewfinder,
    UtensilSpoon: faUtensilSpoon,
    Utensils: faUtensils,
    V: faV,
    VanShuttle: faVanShuttle,
    Vault: faVault,
    VectorSquare: faVectorSquare,
    Venus: faVenus,
    VenusDouble: faVenusDouble,
    VenusMars: faVenusMars,
    Vest: faVest,
    VestPatches: faVestPatches,
    Vial: faVial,
    VialCircleCheck: faVialCircleCheck,
    VialVirus: faVialVirus,
    Vials: faVials,
    VideoSlash: faVideoSlash,
    Vihara: faVihara,
    Virus: faVirus,
    VirusCovid: faVirusCovid,
    VirusCovidSlash: faVirusCovidSlash,
    VirusSlash: faVirusSlash,
    Voicemail: faVoicemail,
    Volcano: faVolcano,
    VolumeXmark: faVolumeXmark,
    VrCardboard: faVrCardboard,
    WandMagic: faWandMagic,
    WandMagicSparkles: faWandMagicSparkles,
    WandSparkles: faWandSparkles,
    Warehouse: faWarehouse,
    Water: faWater,
    WaterLadder: faWaterLadder,
    WaveSquare: faWaveSquare,
    WeightHanging: faWeightHanging,
    WeightScale: faWeightScale,
    Wheelchair: faWheelchair,
    WhiskeyGlass: faWhiskeyGlass,
    Wifi: faWifi,
    Wind: faWind,
    WineBottle: faWineBottle,
    WineGlass: faWineGlass,
    WineGlassAlt: faWineGlassAlt,
    WonSign: faWonSign,
    Worm: faWorm,
    X: faX,
    XRay: faXRay,
    Xmark: faXmark,
    XmarksLines: faXmarksLines,
    YenSign: faYenSign,
    YinYang: faYinYang,
};

